### ISSUE TITLE
Comparison with Transformers.js?

### ISSUE THREAD

**Issue by aehlke** [rahuldshetty/llm.js#5]
https://github.com/xenova/transformers.js

**Comment by rahuldshetty** [comment]
Well for starters, I'm focusing llm.js to provide support for all kinds Large Language Models like llama/vacuna/etc. At the moment it is limited to run medium scaled models in the LLM space. Also transformer.js, uses ONNX as backend engine while I've custom engine for different mode format and types. At the moment, I don't plan to add in other modality tasks (speech/image/multi-modal/etc) YET.

**Comment by aehlke** [comment]
Thanks for elaborating
